### PR TITLE
Updated spin keyframes to specify 'from'

### LINKED ISSUE #68: `spin` broken in Safari
Using Safari v15.4, `spin` property does not work. Tested on https://templarian.github.io/@mdi/react/

@Templarian have you had an opportunity to investigate this issue?

### PR DESCRIPTION
**Pull request by ngburke**
Newer versions of Safari were not happy with keyframes omitting the `from` designation. Added in `from { transform: rotate(0deg) }` in the appropriate spots. Confirmed `spin` now working on Safari 15.4 with this PR. 

Resolves #68  

Other notes:
- The `npm install` step bumped the lockfile version to 2 and dragged in a bunch more metadata.
- The build step caused some whitespace changes on `dist/*.ts`

### CODE REVIEW

**Comment by ngburke** [comment]
@Templarian bump 😄

**Comment by Templarian** [comment]
@ngburke Oh how did I forget to do this. Sorry!!!

Need to push a new version of `@mdi/react` next.

**Comment by Templarian** [comment]
Released `1.6.1`

**Comment by ngburke** [comment]
> Released `1.6.1`

Thank you!

**Pull request merged**
