### PR TITLE
run npm command to update Icon.js

### PR DESCRIPTION
**Pull request by weishiji**

### CODE REVIEW

**Comment by weishiji** [comment]
Can you merge this pull request and update NPM

**Comment by Templarian** [comment]
Thanks for bringing this to my attention!

Closing this PR, since I'm updating the packages and verifying everything is good. Working on publishing a new version right now after testing.  Just got back from  MS Build/vacation.

**Comment by Templarian** [comment]
@weishiji Updated all dependencies and published as `1.1.1`.

**Comment by weishiji** [comment]
> @weishiji Updated all dependencies and published as `1.1.1`.

Thanks!

**Pull request closed without merging**
